### ISSUE TITLE
Don't see behavior in jsfiddle

### ISSUE THREAD

**Issue by solugebefola** [lukeed/preact-scroll-header#1]
I checked out the link from the README, but it's not displaying the expected behavior.  The header element is not fixing to the top of the screen, nor is it appearing when scrolling up.

**Comment by lukeed** [comment]
Ah, I forgot about this component. This was made with Preact 7 and hasn't been updated since. IIRC the demo uses a 'latest' link for Preact

**Comment by solugebefola** [comment]
np

**Comment by lukeed** [comment]
Hey, I went ahead & updated the component.

Both JSFiddle demos now work correctly. Thanks for the heads up!
